-- 如果表已存在則刪除
DROP TABLE IF EXISTS CURRENCY_INFO;

-- 創建 CURRENCY_INFO 表
CREATE TABLE CURRENCY_INFO (
    CUR_CODE VARCHAR(10) PRIMARY KEY,
    NAME_ZH VARCHAR(64) NOT NULL,
    SYMBOL VARCHAR(10),
    CUR_TYPE VARCHAR(20) NOT NULL,
    IS_ACTIVE VARCHAR(2) NOT NULL,
    DISPLAY_SCALE INTEGER
);

CREATE INDEX IDX_CURRENCY_INFO_CUR_TYPE ON CURRENCY_INFO(CUR_TYPE);